_schema: _schema
source: /
paths:
  uploads: public/uploads
  static: public
collections_config:
  about:
    path: src/content/about
    name: About
    icon: bolt
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  authors:
    path: src/content/authors
    name: Authors
    icon: person
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    name: Blog
    icon: event_available
    disable_url: false
    description: ''
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
      text:
        allow_custom_markup: true
        remove_custom_markup: false
        bold: true
        copyformatting:
        italic: true
        link: true
        paths:
        redo:
        removeformat:
        strike: true
        subscript: true
        superscript: true
        underline: true
        undo:
      block:
        allow_custom_markup: false
        remove_custom_markup: false
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code:
        copyformatting:
        embed:
        expandable: false
        format: p, h1, h2, h3, h4, h5, h6, pre, address, div
        height:
        horizontalrule:
        image: true
        image_size_attributes: true
        indent: true
        italic: true
        justify:
        left:
        link:
        mime_type:
        numberedlist:
        outdent:
        paths:
        redo:
        removeformat:
        resize_style:
        right:
        snippet:
        strike:
        styles:
        subscript:
        superscript:
        table:
        underline:
        undo:
        width:
      image:
        expandable:
        height:
        image_size_attributes: true
        mime_type:
        paths:
        resize_style:
        width:
      link:
        paths:
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      Blog Post:
        path: blob/main/cloudcannon.config.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Blog Post
        icon: add_notes
        preview:
        _editables:
          text:
            allow_custom_markup: true
            remove_custom_markup: false
            bold:
            copyformatting:
            italic:
            link:
            paths:
            redo:
            removeformat:
            strike:
            subscript:
            superscript:
            underline:
            undo:
          content:
            allow_custom_markup: false
            remove_custom_markup: false
            blockquote:
            bold:
            bulletedlist:
            center:
            code:
            copyformatting:
            embed:
            expandable:
            format:
            height:
            horizontalrule:
            image:
            image_size_attributes: true
            indent:
            italic:
            justify:
            left:
            link:
            mime_type:
            numberedlist:
            outdent:
            paths:
            redo:
            removeformat:
            resize_style:
            right:
            snippet:
            strike:
            styles:
            subscript:
            superscript:
            table:
            underline:
            undo:
            width:
          image:
            expandable:
            height:
            image_size_attributes: true
            mime_type:
            paths:
            resize_style:
            width:
          link:
            paths:
        _enabled_editors:
          - visual
        _inputs:
        _select_data:
        _structures:
        create:
          path: https://github.com/mognify/taisharyu/tree/main/src/content/blog
          extra_data:
          publish_to:
          _inputs:
          _select_data:
          _structures:
        new_preview_url: taisharyu.us/preview
  docs_1:
    path: src/content/docs
    name: Docs 1
    icon: dock
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  home:
    path: src/content/home
    name: Home
    icon: home
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  index_cards:
    path: src/content/index-cards
    name: Index Cards
    icon: add_card
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  poetry:
    path: src/content/poetry
    name: Poetry
    icon: pets
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  portfolio:
    path: src/content/portfolio
    name: Portfolio
    icon: portrait
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  recipes:
    path: src/content/recipes
    name: Recipes
    icon: local_dining
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  terms:
    path: src/content/terms
    name: Terms
    icon: lens
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs:
    path: docs
    name: Docs
    icon: dock
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
timezone: America/Chicago
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
